sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t sanjayvrs/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sanjayvrs/docker-react npm run test


